### ISSUE TITLE
Question regarding one-to-many redis transport

### ISSUE THREAD

**Issue by otaviosoares** [rjrodger/seneca-redis-transport#17]
Hello, I have a question about redis transport implementation. I'm trying to understand when to use which type of transport, so it can fit my needs and scale well. 

I understand that it works as a broadcast, sending messages to all subscribers. I'm also aware of PR #6 which adds the "handle once" feature that could change this. The question is: imagine I need to run multiple versions of the same service, using redis transport, each instance of the service would subscribe and handle the messages. When would one want this behaviour? 

I'm probably missing the point here, can anyone explain it to me?

Thank very much.

**Comment by geek** [comment]
@otaviosoares do you want to handle a message only once?  As in, the first service to process and acknowledge the message wins, or do you want for each service to process every message?

**Comment by otaviosoares** [comment]
@geek Yes, I want it to be handled once. Although I'm not an MQ expert, it seems the most reasonable to me. But I'd love to hear when the other scenario applies.

Thank you

**Comment by geek** [comment]
@otaviosoares you may want to consider https://github.com/disintegrator/seneca-amqp-transport as it has less of the broadcast behavior and more of the ability to send to individual topic queues.

**Comment by otaviosoares** [comment]
@geek Thank you for pointing me to the right direction.
